name: primihub github bazel actions

on:
  push:
    branches: 
      - develop
      - feature/workflow

jobs:
  job-build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.12
      with:
        cmake-version: '3.20.2'
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Install python-devel
      run: sudo apt install python-dev
    - uses: bazelbuild/setup-bazelisk@v2
    - run: |
        # cc_binary
        bazel build --config=linux :node
      